### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [SaeGon-Heo/Clock-On-Screen-android#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by SaeGon-Heo** [comment]
@mansya Sorry too late.
I'm just surprised that I got a contribution.
Making icon is not simple as I know.
And if you made icon for me, your icon will be belonged under Apache 2.0 License because my repo is under Apache 2.0 License.
If you don't mind about that, new icon what you made will be my pleasure.
Also you will not need any permission.

Thanks for your consideration.

**Comment by SaeGon-Heo** [comment]
Close due to no response for a long time.
