### ISSUE TITLE
Display clock when phone screen is off, and the implementation of analog clock

### ISSUE THREAD

**Issue by cckole** [SaeGon-Heo/Clock-On-Screen-android#2]
### Proposals
-    Display clock when phone screen is off: Yes, I love the way the app displays time and other stuff depending on what is set by the user. However, they all disappear when the phone light sleeps. I would love to see the time, date and so on, displayed on the screen even when the screen is off. This will be a nice improvement if implemented. 

![screen off](https://user-images.githubusercontent.com/36272218/60931308-00551d80-a2b1-11e9-9d63-91638f859266.png)

-    Enable analog clock: The digital time is beautiful, but having the analog as well will be cool for users to select from. They will be able to switch depending on their choice.

![ANALog ND DIGITAL](https://user-images.githubusercontent.com/36272218/60931338-1d89ec00-a2b1-11e9-8c9d-354e10c58be7.png)

### Benefits
Even when phone screen is off, users will not have to press any button on the phone to check the time or whatever info set on the screen. It also beautifies the screen. You can see that from the images.
Having the analog clock will also be a nice implementation. It will complement the analog, and users will be able to select whichever they prefer.

**Comment by SaeGon-Heo** [comment]
**Thanks for your suggestions.**
And I'm so sorry for I think I can't make what you want.

Because...
## Display clock when phone screen is off
> However, they all disappear when the phone light sleeps.

Yes, you right.
"Screen", "Android System" and "Wakelock" is android's most battery consumption as I know.
Because of battery consumption, usually, don't show clock or some stuff when screen is off.

Smartphone vendor use OLED display for save screen's battery consumption.
And OLED doesn't consume much battery when screen is black.

Google made doze mode for save battery which is blocking background tasks from Marshmallow.
You may see https://developer.android.com/training/monitoring-device-state/doze-standby
(Also google adds some of limitations for background tasks from Oreo.)

Because of above ones, Samsung or LG's AOD are basically show a clock on black screen and internally use doze mode completely. They are whitelisted in doze mode.

Actually, I would like to make to see a clock when screen off if possible.
So, I tried to find the way to manage it refer to below links.
https://stackoverflow.com/questions/52990019/how-can-i-allow-android-to-doze-while-my-app-is-open-and-the-screen-is-on
https://stackoverflow.com/questions/48277302/android-o-flag-show-when-locked-is-deprecated
https://gist.github.com/blancnoir-d/ebab7b429e63cb83d2c9ddc421dc9dc2

And experimental output is here.
![1](https://user-images.githubusercontent.com/46312473/60989127-12ea5800-a380-11e9-8c11-fc9536199ae4.PNG)

Comment from [1st link](https://stackoverflow.com/questions/52990019/how-can-i-allow-android-to-doze-while-my-app-is-open-and-the-screen-is-on).
> You cannot have a fully functional doze, with the screen on. It uses power. Doze is to save power.

is saying uses power with screen on implementation.

And I try to go doze mode using adb command, it fail.
Just "ACTIVE"(screen is on), not "IDLE"(screen is off / doze state) as expected.
**This will be produce significant battery consumption mostly.**

## Enable analog clock
For support this, I think it need some graphics stuff and android's canvas APIs for custom canvas drawing.
But I don't have any photoshop skills.

And canvas use bitmap object which use much more ram and cpu/gpu times than text printing.

Also I think there are need to be done some tuning in another way.
Such as,
- refresh clock every minutes not seconds. (no second display / no clock refresh on every second)
- divide the hands of the clock for memory allocation optimization.
- there are no need clock components and some options which "clock on screen" has.
- consider use of hardware acceleration for canvas which produce more quality but may make device hot.
- graphic resources will make app size more bigger.

I didn't use canvas API before, too.
So, make a new app for it would be faster then add it in my app.

##
I tried to make this app as possible as lightweight.
I'm really sorry for hear this.

**Comment by cckole** [comment]
Thank you for your extensive feed back. I understand everything you discussed and im very pleased you understand the fact that, they are possible but due to some limitations, it might not work for this app at the moment. Thank you for replying. Maybe you can put it into consideration in your subsequent development of another project. Still using the app and I love it. Great work buddy.

**Comment by SaeGon-Heo** [comment]
Thank you for everything. Have a good weekend.
